function mostraDescritores(areaOrd,area1Rcm,metrica,areaRP,perimetro,eixoMaior,eixoMenor,ecce)
  disp(strcat("area moeda 1 real em pixel\t"))
  disp(areaOrd(1,1))
  #disp(strcat("area moeda 1 real em centimetros\n",num2str(area1Rcm)))
  disp(strcat("Metrica\n",num2str(metrica)))
  disp("area dos objetos em pixel com regionprops")
  disp(areaRP)
  disp("Perimetro dos objetos em pixel")
  disp(perimetro)
  disp("Eixo maior dos objetos em pixel")
  disp(eixoMaior)
  disp("Eixo menor dos objetos em pixel")
  disp(eixoMenor)
  disp("Eccentricidade dos objetos")
  disp(ecce)
endfunction