function mostraDescritoresCM(areaCM,perimetroCM,eixoMaiorCM,eixoMenorCM)
  disp("area dos objetos em centimetro")
  disp(areaCM)
  disp("Perimetro dos objetos em centimetro")
  disp(perimetroCM)
  disp("Eixo maior dos objetos em centimetro")
  disp(eixoMaiorCM)
  disp("Eixo menor dos objetos em centimetro")
  disp(eixoMenorCM)
endfunction